from pathlib import Path

p = Path('packages/client/src/utils/api-client-history-privacy.ts')
text = p.read_text()
old = """const REDACTED_HISTORY_VALUE = '[REDACTED]';\nconst SENSITIVE_HISTORY_HEADER = /authorization|cookie|(?:api|functions)[-_]?key|(?:auth|access|security)[-_]?token/i;\n\n/** Return whether a header value should never be written verbatim to request history. */\nexport function isSensitiveApiClientHistoryHeader(name: string): boolean {\n  return SENSITIVE_HISTORY_HEADER.test(name);\n}\n"""
new = """const REDACTED_HISTORY_VALUE = '[REDACTED]';\n\nfunction normalizedSensitiveName(name: string): string {\n  return name.trim().toLowerCase().replace(/[^a-z0-9]/g, '');\n}\n\nfunction isSensitiveName(name: string): boolean {\n  const normalized = normalizedSensitiveName(name);\n  return normalized.includes('authorization')\n    || normalized.includes('cookie')\n    || normalized.includes('token')\n    || normalized.includes('signature')\n    || normalized.includes('secret')\n    || normalized.includes('password')\n    || normalized.endsWith('key');\n}\n\n/** Return whether a header value should never be written verbatim to request history. */\nexport function isSensitiveApiClientHistoryHeader(name: string): boolean {\n  return isSensitiveName(name);\n}\n"""
if old not in text:
    raise SystemExit('missing sensitive-header block')
text = text.replace(old, new, 1)
old = """function redactResponseHeaders(headers: Array<[string, string]> | undefined): Array<[string, string]> | undefined {\n  return headers?.map((entry) => isSensitiveApiClientHistoryHeader(entry[0])\n    ? [entry[0], REDACTED_HISTORY_VALUE]\n    : entry);\n}\n\nfunction persistedRequest(request: HttpRequestDraft, omitBody: boolean, stripCredentials: boolean): HttpRequestDraft {\n  const copy = { ...request, headers: redactRequestHeaders(request.headers), ...(stripCredentials ? { auth: sanitizeApiClientAuthCredentials(request.auth) } : {}) };\n"""
new = """function redactQueryEntries(entries: HttpKeyValue[] | undefined): HttpKeyValue[] | undefined {\n  return entries?.map((entry) => isSensitiveName(entry.key)\n    ? { ...entry, value: REDACTED_HISTORY_VALUE }\n    : entry);\n}\n\nfunction redactResponseHeaders(headers: Array<[string, string]> | undefined): Array<[string, string]> | undefined {\n  return headers?.map((entry) => isSensitiveApiClientHistoryHeader(entry[0])\n    ? [entry[0], REDACTED_HISTORY_VALUE]\n    : entry);\n}\n\nfunction redactUrlQuery(url: string): string {\n  const hashIndex = url.indexOf('#');\n  const fragment = hashIndex >= 0 ? url.slice(hashIndex) : '';\n  const withoutFragment = hashIndex >= 0 ? url.slice(0, hashIndex) : url;\n  const queryIndex = withoutFragment.indexOf('?');\n  if (queryIndex < 0) return url;\n  const base = withoutFragment.slice(0, queryIndex);\n  const query = withoutFragment.slice(queryIndex + 1).split('&').map((part) => {\n    if (!part) return part;\n    const equals = part.indexOf('=');\n    const rawName = equals >= 0 ? part.slice(0, equals) : part;\n    let name = rawName;\n    try { name = decodeURIComponent(rawName.replace(/\\+/g, ' ')); } catch { /* preserve malformed query keys */ }\n    return isSensitiveName(name) ? `${rawName}=${encodeURIComponent(REDACTED_HISTORY_VALUE)}` : part;\n  }).join('&');\n  return `${base}?${query}${fragment}`;\n}\n\nfunction persistedRequest(request: HttpRequestDraft, omitBody: boolean, stripCredentials: boolean): HttpRequestDraft {\n  const copy = {\n    ...request,\n    url: redactUrlQuery(request.url),\n    query: redactQueryEntries(request.query),\n    headers: redactRequestHeaders(request.headers),\n    ...(stripCredentials ? { auth: sanitizeApiClientAuthCredentials(request.auth) } : {}),\n  };\n"""
if old not in text:
    raise SystemExit('missing persistence helper block')
text = text.replace(old, new, 1)
old = """      const bodyFree = {\n        ...entry,\n        request: persistedRequest(entry.request, omitBody, stripCredentials),\n        responseHeaders: redactResponseHeaders(entry.responseHeaders),\n      };\n"""
new = """      const bodyFree = {\n        ...entry,\n        resolvedUrl: redactUrlQuery(entry.resolvedUrl),\n        request: persistedRequest(entry.request, omitBody, stripCredentials),\n        responseHeaders: redactResponseHeaders(entry.responseHeaders),\n      };\n"""
if old not in text:
    raise SystemExit('missing history entry snapshot block')
text = text.replace(old, new, 1)
p.write_text(text)
