flexdoc.path=/docs
flexdoc.spec-url=/v3/api-docs
flexdoc.spec-location=classpath:/openapi.json
flexdoc.title=FlexDoc Spring 3.0 showcase
flexdoc.theme=system
flexdoc.try-it-enabled=true
flexdoc.expand=interactive
flexdoc.try-it-default-server=http://localhost:8080
flexdoc.try-it-credentials=same-origin
flexdoc.try-it-api-client-persistence-key=flexdoc-spring-3-showcase
flexdoc.runtime-intelligence=true
